services:
  data_collector:
    build: data_collector/
    env_file:
      - data_collector/.env
    depends_on:
      - db

  api:
    build: api/
    ports:
      - "5000:5000"
    env_file:
      - api/.env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: dollar
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  show:
    image: postgres
    env_file:
      - data_collector/.env
    depends_on:
      - db
    entrypoint: ["/bin/sh", "/scripts/check_db_postgres.sh"]
    volumes:
      - ./check_db_postgres.sh:/scripts/check_db_postgres.sh
